global:
  defaultStorageClass: "local-storage"

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8s-worker02.internal.poorlythoughtout.com
ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: accounts.paircoded.com
  tls: true
  extraTls:
  - hosts:
    - accounts.paircoded.com
    secretName: "wildcard-paircoded-com"


adminIngress:
  enabled: true
  ingressClassName: "nginx"
  hostname: accounts-admin.paircoded.com
  hostnameStrict: true
  tls: true
  extraTls:
  - hosts:
    - accounts-admin.paircoded.com
    secretName: "wildcard-paircoded-com"

